coordinate/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    home
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('course/', include('coursePlanner.urls')),
    path('users/', include('users.urls')),
]

coursePlanner/urls.py
from django.urls import path

from . import views

app_name = 'coursePlanner'
urlpatterns = [
    path('all/', views.courses, name='courses'),
    path('new/', views.newCourse, name='newCourse'),
    path('<int:course_id>/', views.course, name='course'),
    path('<int:course_id>/new-contact/', views.newContact, name='newContact'),
    path('<int:course_id>/new-link/', views.newLink, name='newLink'),
    path('<int:course_id>/new-query/', views.newQuery, name='newQuery'),
    path('<int:course_id>/new-assessment/', views.newAssessment, name='newAssessment'),
    path('<int:course_id>/edit-contact/<int:contact_id>/', views.editContact, name='editContact'),
    path('<int:course_id>/edit-link/<int:link_id>/', views.editLink, name='editLink'),
    path('<int:course_id>/edit-query/<int:query_id>/', views.editQuery, name='editQuery'),
    path('<int:course_id>/edit-assessment/<int:assessment_id>/', views.editAssessment, name='editAssessment'),
    path('<int:course_id>/delete-contact/<int:contact_id>/', views.deleteContact, name='deleteContact'),
    path('<int:course_id>/delete-link/<int:link_id>/', views.deleteLink, name='deleteLink'),
    path('<int:course_id>/delete-query/<int:query_id>/', views.deleteQuery, name='deleteQuery'),
    path('<int:course_id>/delete-assessment/<int:assessment_id>/', views.deleteAssessment, name='deleteAssessment'),
    path('all/delete-course/<int:course_id>/', views.deleteCourse, name='deleteCourse'),
    
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

coursePlanner/models.py
from typing import Optional
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Course(models.Model):
    courseCode = models.CharField(max_length=20)
    courseName = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        # Return a string representation of the model
        return self.courseCode

class Contact(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    role = models.CharField(max_length=300)
    name = models.CharField(max_length=150)
    email = models.CharField(max_length=320)
    location = models.CharField(max_length=500)

    def __str__(self):
        return self.name

class Link(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    link = models.CharField(max_length=1000)
    title = models.CharField(max_length=500)

    def __str__(self):
        return self.title

class Query(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    text = models.TextField()

    class Meta:
        verbose_name_plural = 'queries'

    def __str__(self):
        return f"{self.text[:50]}..."

class Assessment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    task = models.CharField(max_length=100)
    weighting = models.IntegerField()
    myGrade = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.task 

coursePlanner/forms.py
from typing import NewType
from django import forms



from .models import (
    Assessment, 
    Course,
    Contact,
    Link,
    Query,
)


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['courseCode', 'courseName']
        labels = {
            'courseCode': 'Course Code',
            'courseName': 'Course Name',
        }
        widgets = {
            'courseCode' : forms.TextInput(attrs = {'placeholder': 'Course Code'}),
            'courseName' : forms.TextInput(attrs = {'placeholder': 'Course Name'}),
        }

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['role', 'name', 'email', 'location']
        labels = {
            'role': 'Role',
            'name': 'Name',
            'email': 'Email',
            'location': 'Location',
        }
        widgets = {
            'role' : forms.TextInput(attrs = {'placeholder': 'Role'}),
            'name'    : forms.TextInput(attrs = {'placeholder': 'Name'}),
            'email'    : forms.TextInput(attrs = {'placeholder': 'Email'}),
            'location'    : forms.TextInput(attrs = {'placeholder': 'Location'}),
        }

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['link', 'title']
        labels = {
            'link': 'Link',
            'title': 'Title',
        }
        widgets = {
            'link' : forms.TextInput(attrs = {'placeholder': 'Link'}),
            'title'    : forms.TextInput(attrs = {'placeholder': 'Title'}),
        }

class QueryForm(forms.ModelForm):
    class Meta:
        model = Query
        fields = ['text']
        labels = {
            'text': 'Query'
        }


class AssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment
        fields = ['task', 'weighting', 'myGrade']
        labels = {
            'task': 'Task',
            'weighting': 'Weighting',
            'myGrade': 'My Grade',
        }
        widgets = {
            'task' : forms.TextInput(attrs = {'placeholder': 'Assignment 1'}),
            'weighting'    : forms.TextInput(attrs = {'placeholder': '15%'}),
            'myGrade'    : forms.TextInput(attrs = {'placeholder': '80%'}),
        }

    def clean_myGrade(self):
        grade = self.cleaned_data.get("myGrade")
        if type(grade) is int:
            if grade > 100 or grade < 0:
                raise forms.ValidationError("Grade must be in the range of 0 - 100")
            else:
                return grade

    # def clean_weighting(self):

    #     assessments = Assessment.objects.all()
    #     total = 0
    #     for assessment in assessments:
    #         total += assessment.weighting
        
    #     weighting = self.cleaned_data.get("weighting")

    #     if len(self.initial) != 0: # the form was not blank at first (aka. edit) 
    #         oldWeighting = self.initial['weighting']
    #         if weighting + total - oldWeighting > 100:
    #            raise forms.ValidationError("Total weighting must not exceed 100")
    #         else:
    #             return weighting
        
    #     # the form was blank at first (aka. new)
    #     if (weighting + total) > 100:
    #         raise forms.ValidationError("Total weighting must not exceed 100")
    #     else:
    #         return weighting

class DeleteContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = []

class DeleteLinkForm(forms.ModelForm):
    class Meta:
        model = Link 
        fields = []

class DeleteAssessmentForm(forms.ModelForm):
    class Meta:
        model = Assessment 
        fields = []
        
class DeleteQueryForm(forms.ModelForm):
    class Meta:
        model = Query 
        fields = []

class DeleteCourseForm(forms.ModelForm):
    class Meta:
        model = Course 
        fields = []

coursePlanner/views.py
import math
from django.http.response import Http404
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import (
    Course,
    Contact,
    Link, 
    Query,
    Assessment,
)
from .forms import (
    CourseForm,
    ContactForm,
    LinkForm,
    QueryForm,
    AssessmentForm,
    DeleteContactForm,
    DeleteLinkForm,
    DeleteQueryForm,
    DeleteAssessmentForm,
    DeleteCourseForm,
)


def Reverse(lst): 
    return [ele for ele in reversed(lst)] 

@login_required
def courses(request):
    courses = Reverse(Course.objects.filter(owner=request.user))
    # course = Course.objects.create(courseCode = "111", courseName = "111", owner=request.user)
    # course.save()
    context = {'courses': courses}
    templateName = 'coursePlanner/courses.html'
    return render(request, templateName, context)

@login_required
def newCourse(request):
    form = CourseForm(request.POST or None)
    courses = Reverse(Course.objects.filter(owner=request.user))
    if form.is_valid():
        newCourse = form.save(commit=False)
        newCourse.owner = request.user
        newCourse.save()
        return redirect('coursePlanner:courses')
    
    # Display the blank or invalid form
    context = {
        'form': form,
        'courses': courses }
    templateName = 'coursePlanner/new-course.html'
    return render(request, templateName, context)

@login_required
def deleteCourse(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    courseToDelete = Course.objects.get(id=course_id)

    courses = Reverse(Course.objects.filter(owner=request.user))
    
    form = DeleteCourseForm(request.POST or None)
    if form.is_valid():
        courseToDelete.delete()
        return redirect('coursePlanner:courses')
        
    # Display the blank or invalid form
    context = {
        'courses': courses,
        'courseToDelete': courseToDelete,
    }
    templateName = 'coursePlanner/delete-course.html'
    return render(request, templateName, context) 


@login_required
def course(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()

    assessmentMessages = genAssessmentMessages(course_id)

    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments,
        'assessmentMessages': assessmentMessages,
        }
    templateName = 'coursePlanner/course.html'
    return render(request, templateName, context)



@login_required
def newContact(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()
    
    form = ContactForm(request.POST or None)
    if form.is_valid():
        newContact = form.save(commit=False)
        newContact.course = course
        newContact.save()
        return redirect('coursePlanner:course', course_id=course_id)
        
    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form
        }
    templateName = 'coursePlanner/new-contact.html'
    return render(request, templateName, context)

@login_required
def newLink(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()
    
    form = LinkForm(request.POST or None) 
    if form.is_valid():
        newLink = form.save(commit=False)
        newLink.course = course
        newLink.save()
        return redirect('coursePlanner:course', course_id=course_id)
    
    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form,
        }
    templateName = 'coursePlanner/new-link.html'
    return render(request, templateName, context)

@login_required
def newQuery(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()
    
    form = QueryForm(request.POST or None)
    if form.is_valid():
        newQuery = form.save(commit=False)
        newQuery.course = course
        newQuery.save()
        return redirect('coursePlanner:course', course_id=course_id)
    
    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form,
        }
    templateName = 'coursePlanner/new-query.html'
    return render(request, templateName, context)

@login_required
def newAssessment(request, course_id):
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()
    
    # Add a new assessment
    form = AssessmentForm(request.POST or None)
    if form.is_valid():
        newAssessment = form.save(commit=False)
        newAssessment.course = course
        newAssessment.save()
        return redirect('coursePlanner:course', course_id=course_id)

    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form,
        }
    templateName = 'coursePlanner/new-assessment.html'
    return render(request, templateName, context)

@login_required
def editContact(request, course_id, contact_id):
    """Edit an existing contact."""
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    contact = Contact.objects.get(id=contact_id)
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()
 
    form = ContactForm(request.POST or None, instance=contact)
    if form.is_valid():
        form.save()
        return redirect('coursePlanner:course', course_id=course_id)

    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form,
        'contactToEdit': contact,
    }
    templateName = 'coursePlanner/edit-contact.html'
    return render(request, templateName, context)

@login_required
def editLink(request, course_id, link_id):
    """Edit an existing link."""
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    link = Link.objects.get(id=link_id)
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()

    form = LinkForm(request.POST or None, instance=link)
    if form.is_valid():
        form.save()
        return redirect('coursePlanner:course', course_id=course_id)

    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form,
        'linkToEdit': link,
    }
    templateName = 'coursePlanner/edit-link.html'
    return render(request, templateName, context)
    
@login_required
def editQuery(request, course_id, query_id):
    """Edit an existing query."""
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    query = Query.objects.get(id=query_id)
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()

 
    form = QueryForm(request.POST or None, instance=query)
    if form.is_valid():
        form.save()
        return redirect('coursePlanner:course', course_id=course_id)

    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,
        'links': links,
        'queries': queries,
        'assessments': assessments, 
        'form': form,
        'queryToEdit': query,
    }
    templateName = 'coursePlanner/edit-query.html'
    return render(request, templateName, context)


@login_required
def editAssessment(request, course_id, assessment_id):
    """Edit an existing query."""
    course = Course.objects.get(id=course_id)
    if course.owner != request.user:
        raise Http404
    assessment = Assessment.objects.get(id=assessment_id)
    contacts = course.contact_set.all()
    links = course.link_set.all()
    queries = course.query_set.all()
    assessments = course.assessment_set.all()

    form = AssessmentForm(request.POST or None, instance=assessment)
    if form.is_valid():
        form.save()
        return redirect('coursePlanner:course', course_id=course_id)

    # Display the blank or invalid form
    context = {
        'course': course, 
        'contacts': contacts,

coursePlanner/templates/coursePlanner/course.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>{{ course.courseCode }}: {{course.courseName }}</p>

<h2 class="courseHeading">Course Contacts <a href="{% url 'coursePlanner:newContact' course.id %}">
  <img src="{% static 'images/plus.svg' %}" class="add-btn"></a></h2>
<div class="card-list">
  {% for contact in contacts %}     
    <div class="card {% cycle 'blue-purple'  'coral' 'sky-blue'   'teal' %}">
      {% block editContact %}

      <header>
      {{ contact.role }}
      </header>
      
      <div class="card-text-medium">{{ contact.name }}</div>
      <div class="card-text-small">{{ contact.email }}</div>
      <div class="card-text-small">{{ contact.location }}</div>

      <a href="{% url 'coursePlanner:editContact' course_id=course.id contact_id=contact.id %}">
        <i class="far fa-edit"></i></a>
       {% endblock editContact %}
   
      {% block deleteContact %}
      <a href="{% url 'coursePlanner:deleteContact' course_id=course.id contact_id=contact.id %}">
      <i class="far fa-trash-alt"></i></a>
      {% endblock deleteContact %}
    </div>

  {% endfor %}
  
  {% block newContact %}
  {% endblock newContact %}

</div>



<h2 class="courseHeading">Links <a href="{% url 'coursePlanner:newLink' course.id %}">
  <img src="{% static 'images/plus.svg' %}" class="add-btn">
  </a>
</h2>

<ul>
  {% for link in links %}
    {% block editLink %}
      <a href={{link.link}} target="_blank">
        <div class="link">
          <p> <i class="fas fa-link purple"></i> {{link.title}}</p>
          <div>
            <a href="{% url 'coursePlanner:editLink' course_id=course.id link_id=link.id %}">
              <i class="far fa-edit"></i></a>
            {% endblock editLink %}
      
            {% block deleteLink %}
              <a href="{% url 'coursePlanner:deleteLink' course_id=course.id link_id=link.id %}">
              <button><i class="far fa-trash-alt"></i></button></a>
            {% endblock deleteLink %}
          </div>
        </div>
      </a>

  {% endfor %}
</ul>   
 
{% block newLink %}
<p></p>
{% endblock newLink %}


<h2 class="courseHeading">Assessments <a href="{% url 'coursePlanner:newAssessment' course.id %}">
  <img src="{% static 'images/plus.svg' %}" class="add-btn"></a></h2>

<table class="assessment-table">
  <tr class="assessment-header-row">
    <th>Task</th>
    <th>Weighting</th>
    <th>My Grade</th>
    <th></th>
  </tr>
  {% for assessment in assessments %}
    <tr>
      {% block editAssessment %}
        <td>{{ assessment.task }}</td>
        <td>{{ assessment.weighting }}%</td>
        {% if  assessment.myGrade is None %} 
        <td></td> 
        {% else %}
        <td>{{ assessment.myGrade }}%</td>
        {% endif %} 

        <td><a href="{% url 'coursePlanner:editAssessment' course_id=course.id assessment_id=assessment.id %}">
          <button><i class="far fa-edit"></i></button></a>
          {% block deleteAssessment %}
          <a href="{% url 'coursePlanner:deleteAssessment' course_id=course.id assessment_id=assessment.id %}">
            <button><i class="far fa-trash-alt"></i></button></a>
          {% endblock deleteAssessment %}
        </td>
      {% endblock editAssessment %}


    </tr>
  {% endfor %}

{% block newAssessment %}
</table>
{% endblock newAssessment %}

{% if assessmentMessages %}
  <div class="assessment-advice-box">
    <h3>What you need to score in the final assessment:*</h3>
    <div class="assessment-advice">

      {% for message in assessmentMessages %}
      <div class="advice">
        <span class="{% cycle 'ps' 'cr' 'dn' 'hd' %}">
        </span>
        <span>
          {{ message }}
        </span>
      </div>
      {% endfor %}
    </div>
    <p><i>*Assumes there is no double pass requirement or scaling.</i></p>
  </div>
{% endif %}
<!-- <ul>
  {% for message in assessmentMessages %}
    <li>{{ message }}</li>
  {% endfor %}
</ul> -->


<h2 class="courseHeading">Queries <a href="{% url 'coursePlanner:newQuery' course.id %}">
  <img src="{% static 'images/plus.svg' %}" class="add-btn"></a></h2> 

{% for query in queries %}
  <div class="query-container">
    <div class="query-bubble">
      <div class="query-bubble__question-mark">?</div>
      
      <div class="query-bubble__tick">
        <a href="{% url 'coursePlanner:deleteQuery' course_id=course.id query_id=query.id %}">
          <button></button><i class="far fa-check-circle"></i>
        </a>
      </div>

    </div>
    <div class="query">
      {% block editQuery %}
      {{ query.text }}
      <a href="{% url 'coursePlanner:editQuery' course_id=course.id query_id=query.id %}">
        <button><i class="far fa-edit"></i></button></a>
      {% endblock editQuery %}
      
      {% block deleteQuery %}
      {% endblock deleteQuery %}
    </div>
  </div>
    
  {% endfor %}

{% block newQuery %}
{% endblock newQuery %}


{% endblock content %}

coursePlanner/templates/coursePlanner/courses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

  <h1>Courses 
    <a href="{% url 'coursePlanner:newCourse' %}">
      <img src="{% static 'images/plus.svg' %}" class="add-btn"></a>
  </h1>

  <section class="courseCards">


    {% block newCourse %}
    {% endblock newCourse %}

    {% for course in courses %}
    
    <div class="courseCard {% cycle 'blue-purple'  'coral' 'sky-blue' 'teal'  %}">
      <a href="{% url 'coursePlanner:course' course.id %}" class="courseHeading">
        <h1>{{ course }} </h1>
        <h2>{{ course.courseName }} </h2>
      </a>

      {% block deleteCourse %}
      <a href="{% url 'coursePlanner:deleteCourse' course_id=course.id %}">
        <i class="far fa-trash-alt"></i></a>
      {% endblock deleteCourse %}

    </div>

    {% endfor %}

  </section>

{% endblock content %}

coursePlanner/templates/coursePlanner/delete-assessment.html
{% extends 'coursePlanner/course.html' %}

{% block deleteAssessment %}

  {% if assessment == assessmentToDelete %}
    <form action="{% url 'coursePlanner:deleteAssessment' course_id=course.id assessment_id=assessment.id %}" method="post">
      {% csrf_token %}
        <button type="submit"><i class="far fa-check-circle"></i></button>
        <a href="{% url 'coursePlanner:course' course.id %}">
          <button type="button"><i class="fas fa-ban"></i></button></a>
      </form>

  {% else %}
    <a href="{% url 'coursePlanner:deleteAssessment' course_id=course.id assessment_id=assessment.id %}">
      <button><i class="far fa-trash-alt"></i></button></a>

  {% endif %}

{% endblock deleteAssessment %}

coursePlanner/templates/coursePlanner/delete-query.html
{% extends 'coursePlanner/course.html' %}

{% block deleteQuery %}

  {% if query == queryToDelete %}
    <form action="{% url 'coursePlanner:deleteQuery' course_id=course.id query_id=query.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      {% include 'coursePlanner/form-delete.html' %}

  {% else %}
    <a href="{% url 'coursePlanner:deleteQuery' course_id=course.id query_id=query.id %}">
    <button><i class="far fa-trash-alt"></i></button></a>

  {% endif %}


{% endblock deleteQuery %}

coursePlanner/templates/coursePlanner/edit-assessment.html
{% extends 'coursePlanner/course.html' %}

{% block editAssessment %}

  {% if assessment.id == assessmentToEdit.id %}  

    <form action="{% url 'coursePlanner:editAssessment' course_id=course.id assessment_id=assessment.id %}" method="post">
      {% csrf_token %}
      <tr>
        {{ form.errors }}
        <td>{{ form.task }}</td>
        <td>{{ form.weighting }}%</td>
        <td> {{form.myGrade}}  </td>

        <td><button name="submit"><i class="far fa-check-circle"></i></button>
        </form>




  {% else %} 
    <td>{{ assessment.task }}</td>
    <td>{{ assessment.weighting }}%</td>
    <td>{{ assessment.myGrade }}%</td>
    <td><a href="{% url 'coursePlanner:editAssessment' course_id=course.id assessment_id=assessment.id %}">
     <button><i class="far fa-edit"></button></a></td>

  {% endif %}


{% endblock editAssessment %}

coursePlanner/templates/coursePlanner/edit-contact.html
{% extends 'coursePlanner/course.html' %}

{% block editContact %}

  {% if contact.id == contactToEdit.id %}  

    <form action="{% url 'coursePlanner:editContact' course_id=course.id contact_id=contact.id %}" method="post">
      {% csrf_token %}

      <header>
        {{ form.role }}
      </header>
      
      <div class="card-text-medium">{{ form.name }}</div>
      <div class="card-text-small">{{ form.email }}</div>
      <div class="card-text-small">{{ form.location }}</div>

      {% include 'coursePlanner/form-edit.html' %}


  {% else %}
    

      <header>
      {{ contact.role }}
      </header>
      
      <div class="card-text-medium">{{ contact.name }}</div>
      <div class="card-text-small">{{ contact.email }}</div>
      <div class="card-text-small">{{ contact.location }}</div>

      <a href="{% url 'coursePlanner:editContact' course_id=course.id contact_id=contact.id %}">
          <i class="far fa-edit"></i></a>
  {% endif %}

{% endblock editContact %}

coursePlanner/templates/coursePlanner/edit-link.html
{% extends 'coursePlanner/course.html' %}

{% block editLink %}
  <div class="link inactive-link">

  {% if link.id == linkToEdit.id %}  
  
    <form action="{% url 'coursePlanner:editLink' course_id=course.id link_id=link.id %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      {% include 'coursePlanner/form-edit.html' %}

  {% else %}
    <p>{{link.title}}</p>
    <a href="{% url 'coursePlanner:editLink' course_id=course.id link_id=link.id %}">
      <i class="far fa-edit"></i></a>

  {% endif %}
 
{% endblock editLink %}

coursePlanner/templates/coursePlanner/edit-query.html
{% extends 'coursePlanner/course.html' %}

{% block editQuery %}

  {% if query.id == queryToEdit.id %}  
  
    <form action="{% url 'coursePlanner:editQuery' course_id=course.id query_id=query.id %}" method="post">
      {% csrf_token %}
      {{ form.text }}
      {% include 'coursePlanner/form-edit.html' %}


  {% else %}
    {{ query }}
    <a href="{% url 'coursePlanner:editQuery' course_id=course.id query_id=query.id %}">
      <button><i class="far fa-edit"></i></button></a>

  {% endif %}
 
{% endblock editQuery %}

coursePlanner/templates/coursePlanner/new-assessment.html
{% extends 'coursePlanner/course.html' %}

{% block newAssessment %}
  <!-- form to add a new assessment-->
  <form action="{% url 'coursePlanner:newAssessment' course.id %}" method="post">
    {% csrf_token %}
    <tr>
      <td>{{ form.task }}</td>
      <td>{{ form.weighting }}%</td>
      <td>{{ form.myGrade }}%</td>
      <td><button name="submit"><i class="fas fa-plus-circle"></i></button>
      <a href="{% url 'coursePlanner:course' course.id %}">
        <i class="fas fa-ban"></i>
      </a></td>
    </tr>
  </form> 

    
  </table>

  {{ form.errors }}



{% endblock newAssessment %}

coursePlanner/templates/coursePlanner/new-contact.html
{% extends 'coursePlanner/course.html' %}

{% block newContact %}
<!-- form to add a new contact -->
<form action="{% url 'coursePlanner:newContact' course.id %}" method="post" class="new-card"> 
  {% csrf_token %}
  <div class="card translucent">
    <header>
      {{ form.role }}
    </header>
      
    <div class="card-text-medium">{{ form.name }}</div>
    <div class="card-text-small">{{ form.email }}</div>
    <div class="card-text-small">{{ form.location }}</div>

    {% include 'coursePlanner/form-add.html' %}
  </div>


{% endblock newContact %}