coordinate/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import (
    home
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('course/', include('coursePlanner.urls')),
    path('users/', include('users.urls')),
]

coursePlanner/urls.py
from django.urls import path

from . import views

app_name = 'coursePlanner'
urlpatterns = [
    path('all/', views.courses, name='courses'),
    path('new/', views.newCourse, name='newCourse'),
    path('<int:course_id>/', views.course, name='course'),
    path('<int:course_id>/new-contact/', views.newContact, name='newContact'),
    path('<int:course_id>/new-link/', views.newLink, name='newLink'),
    path('<int:course_id>/new-query/', views.newQuery, name='newQuery'),
    path('<int:course_id>/new-assessment/', views.newAssessment, name='newAssessment'),
    path('<int:course_id>/edit-contact/<int:contact_id>/', views.editContact, name='editContact'),
    path('<int:course_id>/edit-link/<int:link_id>/', views.editLink, name='editLink'),
    path('<int:course_id>/edit-query/<int:query_id>/', views.editQuery, name='editQuery'),
    path('<int:course_id>/edit-assessment/<int:assessment_id>/', views.editAssessment, name='editAssessment'),
    path('<int:course_id>/delete-contact/<int:contact_id>/', views.deleteContact, name='deleteContact'),
    path('<int:course_id>/delete-link/<int:link_id>/', views.deleteLink, name='deleteLink'),
    path('<int:course_id>/delete-query/<int:query_id>/', views.deleteQuery, name='deleteQuery'),
    path('<int:course_id>/delete-assessment/<int:assessment_id>/', views.deleteAssessment, name='deleteAssessment'),
    path('all/delete-course/<int:course_id>/', views.deleteCourse, name='deleteCourse'),
    
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

templates/addBtn.html
<svg xmlns="http://www.w3.org/2000/svg" width="33" height="33" viewBox="0 0 33 33">
  <defs>
    <linearGradient id="addbtn-a" x1="50%" x2="50%" y1="0%" y2="100%">
      <stop offset="0%" stop-color="#7367F0"/>
      <stop offset="100%" stop-color="#CE9FFC"/>
    </linearGradient>
  </defs>
  <g fill="none" fill-rule="evenodd" transform="translate(0 -7)">
    <circle cx="16.5" cy="23.5" r="16.5" fill="url(#addbtn-a)"/>
    <text fill="#FFF" fill-rule="nonzero" font-family="Nunito-Black, Nunito" font-size="33" font-weight="800">
      <tspan x="7" y="33">+</tspan> <tspan x="24" y="33" font-family="Nunito-SemiBold, Nunito" font-size="27" font-weight="500"> </tspan>
    </text>
  </g>
</svg>

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Coordinate</title>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
  {% block head %} {% endblock head %}
</head>
<body>
  <section class="glass">
    <nav class="navbar">
      <div class="nav-item nav-logo">

        <a href="/">
          <!-- {% include 'coordinateLogo.html' %} -->
          <img src="{% static 'images/logo.png' %}" class="logo">
        </a>
        <div class="nav-cursor"></div> 

      </div>

      <div class="nav-item nav-courses courseMenu"> 
        
        <a href="{% url 'coursePlanner:courses' %}">
          <img src="{% static 'images/courseIcon.png' %}">
        </a>

        <div class="nav-cursor"></div> 
        <div class="courseMenuContent">
          <h2>Courses</h2>
          {% for course in courses %}
          <div class="course">
            <a href="{% url 'coursePlanner:course' course.id %}" class="course">{{ course }}</a>
          </div>
          {% endfor %}
          <div>
            <a href="{% url 'coursePlanner:newCourse' %}">
              {% include 'addBtn.html' %}
            </a>
          </div>
        </div>
      </div>
<!-- 
      <div class="nav-item nav-term"> 

        <a href="#">
          <img src="{% static 'images/termIcon.png' %}">
        </a>

        <div class="nav-cursor"></div>

      </div> -->

      {% if user.is_authenticated %}  
      <div class="nav-item">
          <!-- <div class="username">{{ user.username }}</div> -->
          <div><a href="{% url 'users:logout' %}" class="user-btn">Logout</a></div>
      </div>
      
      {% else %}
      <div class="nav-item">
        <a href="{% url 'users:register' %}" class="user-btn">Register</a>
        <div><a href="{% url 'users:login' %}" class="user-btn">Login</a></div>
          
      </div>

      {% endif %}
    </nav>
    
    <main>
      {% block page_header %}{% endblock page_header %}
      {% block content %}{% endblock content %}
    </main>

  </section>

  <script src="{% static 'js/base.js' %}""async defer></script>

</body>

</html>

templates/coordinateLogo.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="75" height="68" viewBox="0 0 75 68">
  <defs>
    <path id="logo-a" d="M32.4383403,35.6016633 C33.8662187,24.3743457 33.8655868,26.7844727 32.4364444,15.5454431 C32.1182604,13.0432033 29.0258403,11.5614848 29.0258403,8.79271916 C29.0258403,4.16587031 32.7754826,0.409186848 37.3940486,0.409186848 C42.0129306,0.409186848 45.7625729,4.16587031 45.7625729,8.79271916 C45.7625729,11.5614848 42.6701528,13.0432033 42.3519687,15.5454431 C40.9474722,26.5904344 40.9468403,24.568384 42.3500729,35.6016633 C43.2572292,36.2679776 44.0433681,37.1289634 44.6415035,38.1662613 C45.2390069,39.2035592 45.5900521,40.3158769 45.7129653,41.4348418 C54.7153299,48.295189 52.6277014,47.0875932 63.0611042,51.4684913 C65.3835,52.4437476 68.2105035,50.5014651 70.6039931,51.8856896 C74.6038854,54.1992723 75.9764687,59.3306841 73.6670278,63.3377498 C71.3579028,67.3448155 66.2353611,68.7198605 62.2354687,66.4062778 C59.8419792,65.0220532 60.1073958,61.5980521 58.1035,60.070752 C49.2584896,53.3306896 51.0055,54.3404486 40.767684,50.0418506 C39.7354028,50.4986162 38.5941111,50.7521638 37.3940486,50.7521638 C36.1943021,50.7521638 35.0530104,50.4986162 34.0207292,50.0418506 C23.602809,54.4157849 25.6853819,53.212304 16.6849132,60.070752 C14.6807014,61.5980521 14.946434,65.0220532 12.5529444,66.4062778 C8.55305208,68.7198605 3.43051042,67.3448155 1.12138542,63.3377498 C-1.18805556,59.3306841 0.184527778,54.1992723 4.18442014,51.8856896 C6.57790972,50.5014651 9.40491319,52.4437476 11.727309,51.4684913 C21.9806076,47.163246 20.2288576,48.1768035 29.0754479,41.4348418 C29.1983611,40.3158769 29.5494062,39.2035592 30.1469097,38.1662613 C30.7450451,37.1289634 31.531184,36.2679776 32.4383403,35.6016633 Z"/>
    <linearGradient id="logo-b" x1="10.863%" x2="100%" y1="38.849%" y2="90.273%">
      <stop offset="0%" stop-color="#7366F0"/>
      <stop offset="100%" stop-color="#CD9EFB"/>
    </linearGradient>
    <path id="logo-d" d="M6.13099886,0.713066667 C9.32500114,0.713066667 11.9179886,3.23434667 11.9179886,6.33962667 C11.9179886,9.44490667 9.32500114,11.9658667 6.13099886,11.9658667 C2.93666743,11.9658667 0.34368,9.44490667 0.34368,6.33962667 C0.34368,3.23434667 2.93666743,0.713066667 6.13099886,0.713066667 Z"/>
    <radialGradient id="logo-e" cx="-164.411%" cy="-251.5%" r="929.514%" fx="-164.411%" fy="-251.5%" gradientTransform="matrix(.97222 0 0 1 -.046 0)">
      <stop offset="0%" stop-color="#7366F0"/>
      <stop offset="100%" stop-color="#CD9EFB"/>
    </radialGradient>
    <path id="logo-g" d="M6.03666667,0.713066667 C9.27133333,0.713066667 11.8973333,3.23434667 11.8973333,6.33962667 C11.8973333,9.44490667 9.27133333,11.9658667 6.03666667,11.9658667 C2.802,11.9658667 0.175666667,9.44490667 0.175666667,6.33962667 C0.175666667,3.23434667 2.802,0.713066667 6.03666667,0.713066667 Z"/>
    <radialGradient id="logo-h" cx="-428.059%" cy="-251.5%" r="941.348%" fx="-428.059%" fy="-251.5%" gradientTransform="matrix(.96 0 0 1 -.171 0)">
      <stop offset="0%" stop-color="#7366F0"/>
      <stop offset="100%" stop-color="#CD9EFB"/>
    </radialGradient>
    <path id="logo-j" d="M6.11533333,0.433706667 C9.35033333,0.433706667 11.9763333,2.95498667 11.9763333,6.06026667 C11.9763333,9.16554667 9.35033333,11.6865067 6.11533333,11.6865067 C2.88066667,11.6865067 0.254666667,9.16554667 0.254666667,6.06026667 C0.254666667,2.95498667 2.88066667,0.433706667 6.11533333,0.433706667 Z"/>
    <radialGradient id="logo-k" cx="-286.546%" cy="-476.516%" r="941.348%" fx="-286.546%" fy="-476.516%" gradientTransform="matrix(.96 0 0 1 -.115 0)">
      <stop offset="0%" stop-color="#7366F0"/>
      <stop offset="100%" stop-color="#CD9EFB"/>
    </radialGradient>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <mask id="logo-c" fill="#fff">
      <use xlink:href="#logo-a"/>
    </mask>
    <path fill="url(#logo-b)" d="M32.4383403,35.6016633 C33.8662187,24.3743457 33.8655868,26.7844727 32.4364444,15.5454431 C32.1182604,13.0432033 29.0258403,11.5614848 29.0258403,8.79271916 C29.0258403,4.16587031 32.7754826,0.409186848 37.3940486,0.409186848 C42.0129306,0.409186848 45.7625729,4.16587031 45.7625729,8.79271916 C45.7625729,11.5614848 42.6701528,13.0432033 42.3519687,15.5454431 C40.9474722,26.5904344 40.9468403,24.568384 42.3500729,35.6016633 C43.2572292,36.2679776 44.0433681,37.1289634 44.6415035,38.1662613 C45.2390069,39.2035592 45.5900521,40.3158769 45.7129653,41.4348418 C54.7153299,48.295189 52.6277014,47.0875932 63.0611042,51.4684913 C65.3835,52.4437476 68.2105035,50.5014651 70.6039931,51.8856896 C74.6038854,54.1992723 75.9764687,59.3306841 73.6670278,63.3377498 C71.3579028,67.3448155 66.2353611,68.7198605 62.2354687,66.4062778 C59.8419792,65.0220532 60.1073958,61.5980521 58.1035,60.070752 C49.2584896,53.3306896 51.0055,54.3404486 40.767684,50.0418506 C39.7354028,50.4986162 38.5941111,50.7521638 37.3940486,50.7521638 C36.1943021,50.7521638 35.0530104,50.4986162 34.0207292,50.0418506 C23.602809,54.4157849 25.6853819,53.212304 16.6849132,60.070752 C14.6807014,61.5980521 14.946434,65.0220532 12.5529444,66.4062778 C8.55305208,68.7198605 3.43051042,67.3448155 1.12138542,63.3377498 C-1.18805556,59.3306841 0.184527778,54.1992723 4.18442014,51.8856896 C6.57790972,50.5014651 9.40491319,52.4437476 11.727309,51.4684913 C21.9806076,47.163246 20.2288576,48.1768035 29.0754479,41.4348418 C29.1983611,40.3158769 29.5494062,39.2035592 30.1469097,38.1662613 C30.7450451,37.1289634 31.531184,36.2679776 32.4383403,35.6016633 Z" mask="url(#logo-c)"/>
    <g transform="translate(18 28)">
      <mask id="logo-f" fill="#fff">
        <use xlink:href="#logo-d"/>
      </mask>
      <path fill="url(#logo-e)" d="M6.13099886,0.713066667 C9.32500114,0.713066667 11.9179886,3.23434667 11.9179886,6.33962667 C11.9179886,9.44490667 9.32500114,11.9658667 6.13099886,11.9658667 C2.93666743,11.9658667 0.34368,9.44490667 0.34368,6.33962667 C0.34368,3.23434667 2.93666743,0.713066667 6.13099886,0.713066667 Z" mask="url(#logo-f)"/>
    </g>
    <g transform="translate(47 28)">
      <mask id="logo-i" fill="#fff">
        <use xlink:href="#logo-g"/>
      </mask>
      <path fill="url(#logo-h)" d="M6.03666667,0.713066667 C9.27133333,0.713066667 11.8973333,3.23434667 11.8973333,6.33962667 C11.8973333,9.44490667 9.27133333,11.9658667 6.03666667,11.9658667 C2.802,11.9658667 0.175666667,9.44490667 0.175666667,6.33962667 C0.175666667,3.23434667 2.802,0.713066667 6.03666667,0.713066667 Z" mask="url(#logo-i)"/>
    </g>
    <g transform="translate(32 53)">
      <mask id="logo-l" fill="#fff">
        <use xlink:href="#logo-j"/>
      </mask>
      <path fill="url(#logo-k)" d="M6.11533333,0.433706667 C9.35033333,0.433706667 11.9763333,2.95498667 11.9763333,6.06026667 C11.9763333,9.16554667 9.35033333,11.6865067 6.11533333,11.6865067 C2.88066667,11.6865067 0.254666667,9.16554667 0.254666667,6.06026667 C0.254666667,2.95498667 2.88066667,0.433706667 6.11533333,0.433706667 Z" mask="url(#logo-l)"/>
    </g>
  </g>
</svg>

templates/courseIcon.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="73" height="80" viewBox="0 0 73 80">
  <defs>
    <linearGradient id="courses-icon-a" x1="50%" x2="50%" y1="0%" y2="100%">
      <stop offset="0%" stop-color="#7367F0"/>
      <stop offset="100%" stop-color="#CE9FFC"/>
    </linearGradient>
    <filter id="courses-icon-b" width="100%" height="100%" x="0%" y="0%" filterUnits="objectBoundingBox">
      <feGaussianBlur in="SourceGraphic"/>
    </filter>
    <linearGradient id="courses-icon-c" x1="21.32%" x2="78.726%" y1="0%" y2="100%">
      <stop offset="0%" stop-color="#FFF" stop-opacity=".2"/>
      <stop offset="100%" stop-color="#FFF" stop-opacity=".8"/>
    </linearGradient>
    <filter id="courses-icon-d" width="100%" height="100%" x="0%" y="0%" filterUnits="objectBoundingBox">
      <feGaussianBlur in="SourceGraphic"/>
    </filter>
    <linearGradient id="courses-icon-g" x1="0%" x2="100%" y1="47.86%" y2="52.14%">
      <stop offset="0%" stop-color="#FFF" stop-opacity=".684"/>
      <stop offset="99.956%" stop-color="#FFF"/>
    </linearGradient>
    <rect id="courses-icon-f" width="29" height="6" x="22" y="34" rx="3"/>
    <filter id="courses-icon-e" width="134.5%" height="266.7%" x="-13.8%" y="-66.7%" filterUnits="objectBoundingBox">
      <feMorphology in="SourceAlpha" operator="dilate" radius=".5" result="shadowSpreadOuter1"/>
      <feOffset dx="1" dy="1" in="shadowSpreadOuter1" result="shadowOffsetOuter1"/>
      <feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation="1"/>
      <feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0.550340834   0 0 0 0 0.581557749   0 0 0 0 0.835752625  0 0 0 1 0"/>
    </filter>
    <linearGradient id="courses-icon-j" x1="0%" x2="100%" y1="45.5%" y2="54.5%">
      <stop offset="0%" stop-color="#FFF" stop-opacity=".684"/>
      <stop offset="99.956%" stop-color="#FFF"/>
    </linearGradient>
    <rect id="courses-icon-i" width="20" height="6" x="22" y="46" rx="3"/>
    <filter id="courses-icon-h" width="150%" height="266.7%" x="-20%" y="-66.7%" filterUnits="objectBoundingBox">
      <feMorphology in="SourceAlpha" operator="dilate" radius=".5" result="shadowSpreadOuter1"/>
      <feOffset dx="1" dy="1" in="shadowSpreadOuter1" result="shadowOffsetOuter1"/>
      <feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation="1"/>
      <feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0.550340834   0 0 0 0 0.581557749   0 0 0 0 0.835752625  0 0 0 1 0"/>
    </filter>
  </defs>
  <g fill="none" fill-rule="evenodd" transform="translate(-4 -2)">
    <rect width="61" height="69" x="10" y="9" fill="url(#courses-icon-a)" filter="url(#courses-icon-b)" rx="16" transform="rotate(19 40.5 43.5)"/>
    <rect width="61" height="69" x="4" y="2" fill="url(#courses-icon-c)" filter="url(#courses-icon-d)" rx="16"/>
    <use fill="#000" filter="url(#courses-icon-e)" xlink:href="#courses-icon-f"/>
    <use fill="url(#courses-icon-g)" xlink:href="#courses-icon-f"/>
    <use fill="#000" filter="url(#courses-icon-h)" xlink:href="#courses-icon-i"/>
    <use fill="url(#courses-icon-j)" xlink:href="#courses-icon-i"/>
  </g>
</svg>

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
{% endblock head %}

{% block page_header %}
{% endblock page_header %}

{% block content %}
<div class="landing">
  <div class="intro">
    <h1>Coordinate</h1>
    <h2>Your personal university study planner</h2>
    <a href="{% url 'coursePlanner:courses' %}">
      <div class="start-btn">
       Start now &raquo 
      </div>
    </a>
  </div>
  <img src="{% static 'images/compassNeedle.svg' %}" class="compass">

</div>

{% endblock content %}

templates/termIcon.html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="79" height="78" viewBox="0 0 79 78">
  <defs>
    <linearGradient id="term-icon-a" x1="50%" x2="50%" y1="0%" y2="100%">
      <stop offset="0%" stop-color="#7367F0"/>
      <stop offset="100%" stop-color="#CE9FFC"/>
    </linearGradient>
    <filter id="term-icon-b" width="100%" height="100%" x="0%" y="0%" filterUnits="objectBoundingBox">
      <feGaussianBlur in="SourceGraphic"/>
    </filter>
    <linearGradient id="term-icon-c" x1="21.32%" x2="78.726%" y1="0%" y2="100%">
      <stop offset="0%" stop-color="#FFF" stop-opacity=".2"/>
      <stop offset="100%" stop-color="#FFF" stop-opacity=".8"/>
    </linearGradient>
    <filter id="term-icon-d" width="100%" height="100%" x="0%" y="0%" filterUnits="objectBoundingBox">
      <feGaussianBlur in="SourceGraphic"/>
    </filter>
    <linearGradient id="term-icon-g" x1="0%" x2="100%" y1="47.531%" y2="52.469%">
      <stop offset="0%" stop-color="#FFF" stop-opacity=".684"/>
      <stop offset="99.956%" stop-color="#FFF"/>
    </linearGradient>
    <rect id="term-icon-f" width="27" height="6" x="16.511" y="38.169" rx="3"/>
    <filter id="term-icon-e" width="137%" height="266.7%" x="-14.8%" y="-66.7%" filterUnits="objectBoundingBox">
      <feMorphology in="SourceAlpha" operator="dilate" radius=".5" result="shadowSpreadOuter1"/>
      <feOffset dx="1" dy="1" in="shadowSpreadOuter1" result="shadowOffsetOuter1"/>
      <feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation="1"/>
      <feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0.550340834   0 0 0 0 0.581557749   0 0 0 0 0.835752625  0 0 0 1 0"/>
    </filter>
    <linearGradient id="term-icon-j" x1="0%" x2="100%" y1="49.185%" y2="50.815%">
      <stop offset="0%" stop-color="#FFF" stop-opacity=".684"/>
      <stop offset="99.956%" stop-color="#FFF"/>
    </linearGradient>
    <rect id="term-icon-i" width="47" height="6" x="21.89" y="45.411" rx="3"/>
    <filter id="term-icon-h" width="121.3%" height="266.7%" x="-8.5%" y="-66.7%" filterUnits="objectBoundingBox">
      <feMorphology in="SourceAlpha" operator="dilate" radius=".5" result="shadowSpreadOuter1"/>
      <feOffset dx="1" dy="1" in="shadowSpreadOuter1" result="shadowOffsetOuter1"/>
      <feGaussianBlur in="shadowOffsetOuter1" result="shadowBlurOuter1" stdDeviation="1"/>
      <feColorMatrix in="shadowBlurOuter1" values="0 0 0 0 0.550340834   0 0 0 0 0.581557749   0 0 0 0 0.835752625  0 0 0 1 0"/>
    </filter>
  </defs>
  <g fill="none" fill-rule="evenodd" transform="translate(-6 -4.05)">
    <rect width="61" height="69" x="15" y="9" fill="url(#term-icon-a)" filter="url(#term-icon-b)" rx="16" transform="rotate(-119 45.5 43.5)"/>
    <rect width="61" height="69" x="10" y="5" fill="url(#term-icon-c)" filter="url(#term-icon-d)" rx="16"/>
    <g transform="rotate(-29 30.011 41.169)">
      <use fill="#000" filter="url(#term-icon-e)" xlink:href="#term-icon-f"/>
      <use fill="url(#term-icon-g)" xlink:href="#term-icon-f"/>
    </g>
    <g transform="rotate(-29 45.39 48.411)">
      <use fill="#000" filter="url(#term-icon-h)" xlink:href="#term-icon-i"/>
      <use fill="url(#term-icon-j)" xlink:href="#term-icon-i"/>
    </g>
  </g>
</svg>